import { ethers } from "hardhat";
import * as fs from "fs";

async function main() {
  const [d] = await ethers.getSigners();
  const a = d.address;
  const dep = JSON.parse(fs.readFileSync("deployments/421614.json", "utf8"));
  console.log("Deployer:", a);
  const Pool = await ethers.getContractFactory("LendingPool");
  const pool = await Pool.deploy();
  const poolTx = pool.deploymentTransaction();
  await pool.waitForDeployment();
  const poolAddr = await pool.getAddress();
  console.log("Pool:", poolAddr, "tx:", poolTx?.hash);
  const PYTH = "0x4374e5a8b9C22271E9EB878A2AA31DE97DF15DAF";
  const Oracle = await ethers.getContractFactory("PriceOracle");
  const oracle = await Oracle.deploy(PYTH, 86400n);
  const oracleTx = oracle.deploymentTransaction();
  await oracle.waitForDeployment();
  const oracleAddr = await oracle.getAddress();
  console.log("Oracle:", oracleAddr, "tx:", oracleTx?.hash);
  const Comp = await ethers.getContractFactory("FheForgeComposer");
  const composer = await Comp.deploy(dep.contracts.StrategyRegistry, dep.contracts.StrategyVault, poolAddr, dep.contracts.SwapRouter);
  const compTx = composer.deploymentTransaction();
  await composer.waitForDeployment();
  const compAddr = await composer.getAddress();
  console.log("Composer:", compAddr, "tx:", compTx?.hash);
  const WETH = "0x9A0227ebC77288ECFc7e6890C4C4e2FB11Af443d";
  await (await pool.setWeth(WETH)).wait();
  console.log("Pool.setWeth done");
  await (await pool.setOracle(oracleAddr)).wait();
  console.log("Pool.setOracle done");
  const USDC = "0x150376EdEbc5AC48771655a61a795d828BeC8Df6";
  const ID = "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace";
  await (await oracle.setSource(WETH, ID, 18, 86400n)).wait();
  await (await oracle.setSource(USDC, ID, 6, 86400n)).wait();
  await (await oracle.setCollateralFactor(USDC, 8000, 8500)).wait();
  await (await oracle.setCollateralFactor(WETH, 8000, 8500)).wait();
  console.log("Oracle feeds set");
  dep.contracts.LendingPool = poolAddr;
  dep.contracts.PriceOracle = oracleAddr;
  dep.contracts.FheForgeComposer = compAddr;
  dep.notes = "Wave 9 full: Pool+Oracle+Composer owned by 0x4855";
  fs.writeFileSync("deployments/421614.json", JSON.stringify(dep, null, 2));
  console.log("DONE");
  console.log("POOL:", poolAddr);
  console.log("ORACLE:", oracleAddr);
  console.log("COMPOSER:", compAddr);
}
main().catch(e => { console.error(e); process.exit(1); });
