version: "3.8"

services:
  fheforge-api:
    build:
      context: ./backend/apps
      dockerfile: Dockerfile
    container_name: fheforge-api
    ports:
      - "3001:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - SUPABASE_URL=https://igxjqbnsubwiqjhtgigi.supabase.co
      - SUPABASE_KEY=${SUPABASE_KEY}
      - COFHE_RPC=https://sepolia-rollup.arbitrum.io/rpc
      - PORT=3000
      - STRATEGY_VAULT_ADDRESS=0xfCb89417e0a21813c84647614764e920bBdFEb94
      - LENDING_POOL_ADDRESS=0xff687831dfD3657D6C6879403cE56f53518b378C
      - PRICE_ORACLE_ADDRESS=0x46ef25fDd66Ce1A331942064Ef6879848621fBd9
      - STRATEGY_REGISTRY_ADDRESS=0xB39E9B573b8f39fBc407f8F7d9F621481d3E12C8
      - COMPOSER_ADDRESS=0xEab68D8Ee6DC5Ddc10293fF3B1bb21679d81dC8b
      - SWAP_ROUTER_ADDRESS=0x9C9bEb3d95184BbA11AfE1D973927562C8eb0409
      - EXECUTOR_ADDRESS=0x1bF7eb45695A4d9b83F5392F16DC262840B4A7d1
      - TOKEN_WETH=0x84BddCAfaccbBDBc0e3F1CAcCDd352EBf5e40A32
      - TOKEN_USDC=0x150376EdEbc5AC48771655a61a795d828BeC8Df6
    volumes:
      - fheforge-api-logs:/app/logs
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  fheforge-api-logs:
