version: "3.8"

services:
  fheforge-api:
    build:
      context: ./backend/apps
      dockerfile: Dockerfile
    container_name: fheforge-api
    ports:
      - "3001:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - SUPABASE_URL=https://igxjqbnsubwiqjhtgigi.supabase.co
      - SUPABASE_KEY=${SUPABASE_KEY}
      - COFHE_RPC=https://sepolia-rollup.arbitrum.io/rpc
      - PORT=3000
      - STRATEGY_VAULT_ADDRESS=0xe9486B12261D02BeB236355934981d49c5697fb3
      - LENDING_POOL_ADDRESS=0x2e04961e0d4448FeeeA5b23593eC81C1C9A2cD2a
      - PRICE_ORACLE_ADDRESS=0x8E41d720173c347740C05011FadD3a3B015ae18c
      - STRATEGY_REGISTRY_ADDRESS=0xEbBD1aFDCC888116a4c3800ec856c8c3b1535374
      - COMPOSER_ADDRESS=0xBcaEF72afA1f207F44C5aa11E48a7bea4b71632C
      - SWAP_ROUTER_ADDRESS=0x5218486A8831b53b509CDF2390b3b6333B4d0bf7
      - EXECUTOR_ADDRESS=0x270F526b27cf7bf810a61e5f14f904C51CdC3deA
      - TOKEN_WETH=0x84BddCAfaccbBDBc0e3F1CAcCDd352EBf5e40A32
      - TOKEN_USDC=0x150376EdEbc5AC48771655a61a795d828BeC8Df6
    volumes:
      - fheforge-api-logs:/app/logs
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  fheforge-api-logs:
