#!/usr/bin/env bash
# sync-addresses.sh — Generate env files from canonical deployment record
# Usage: bash scripts/sync-addresses.sh [chainId]
# Default chainId: 421614 (Arbitrum Sepolia)

set -euo pipefail

CHAIN_ID="${1:-421614}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_JSON="$ROOT/contracts/deployments/${CHAIN_ID}.json"

if [ ! -f "$DEPLOY_JSON" ]; then
  echo "ERROR: Deployment record not found: $DEPLOY_JSON"
  exit 1
fi

# Extract addresses using jq
LENDING_POOL=$(jq -r '.contracts.LendingPool' "$DEPLOY_JSON")
STRATEGY_VAULT=$(jq -r '.contracts.StrategyVault' "$DEPLOY_JSON")
COMPOSER=$(jq -r '.contracts.FheForgeComposer' "$DEPLOY_JSON")
SWAP_ROUTER=$(jq -r '.contracts.SwapRouter' "$DEPLOY_JSON")
PRICE_ORACLE=$(jq -r '.contracts.PriceOracle' "$DEPLOY_JSON")
STRATEGY_REGISTRY=$(jq -r '.contracts.StrategyRegistry' "$DEPLOY_JSON")
STRATEGY_EXECUTOR=$(jq -r '.contracts.StrategyExecutor' "$DEPLOY_JSON")
TOKEN_REGISTRY=$(jq -r '.contracts.TokenRegistry' "$DEPLOY_JSON")
EXECUTOR=$(jq -r '.contracts.ExecutorContract' "$DEPLOY_JSON")
GOVERNOR=$(jq -r '.contracts.FheForgeGovernor // "not-deployed"' "$DEPLOY_JSON")
TIMELOCK=$(jq -r '.contracts.FheForgeTimelock // "not-deployed"' "$DEPLOY_JSON")
WETH=$(jq -r '.tokens.WETH // .weth // "not-set"' "$DEPLOY_JSON")
USDC=$(jq -r '.tokens.USDC // "not-set"' "$DEPLOY_JSON")

echo "=== Contract Addresses (Chain: $CHAIN_ID) ==="
echo "LendingPool:        $LENDING_POOL"
echo "StrategyVault:      $STRATEGY_VAULT"
echo "Composer:           $COMPOSER"
echo "SwapRouter:         $SWAP_ROUTER"
echo "PriceOracle:        $PRICE_ORACLE"
echo "StrategyRegistry:   $STRATEGY_REGISTRY"
echo "StrategyExecutor:   $STRATEGY_EXECUTOR"
echo "TokenRegistry:      $TOKEN_REGISTRY"
echo "ExecutorContract:   $EXECUTOR"
echo "Governor:           $GOVERNOR"
echo "Timelock:           $TIMELOCK"
echo "WETH:               $WETH"
echo "USDC:               $USDC"
echo ""

# Generate Railway variables set command
echo "=== Railway Variables Set Command ==="
echo "railway variables set \\"
echo "  LENDING_POOL_ADDRESS=$LENDING_POOL \\"
echo "  POOL_ADDRESS=$LENDING_POOL \\"
echo "  STRATEGY_VAULT_ADDRESS=$STRATEGY_VAULT \\"
echo "  PRICE_ORACLE_ADDRESS=$PRICE_ORACLE \\"
echo "  TOKEN_REGISTRY_ADDRESS=$TOKEN_REGISTRY \\"
echo "  COMPOSER_ADDRESS=$COMPOSER \\"
echo "  SWAP_ROUTER_ADDRESS=$SWAP_ROUTER \\"
echo "  EXECUTOR_ADDRESS=$EXECUTOR \\"
echo "  STRATEGY_EXECUTOR_ADDRESS=$STRATEGY_EXECUTOR \\"
echo "  STRATEGY_REGISTRY_ADDRESS=$STRATEGY_REGISTRY \\"
echo "  GOVERNOR_ADDRESS=$GOVERNOR \\"
echo "  TIMELOCK_ADDRESS=$TIMELOCK \\"
echo "  TOKEN_WETH=$WETH \\"
echo "  TOKEN_USDC=$USDC"
echo ""

# Generate .env.production.example
cat > "$ROOT/backend/apps/.env.production.example" <<ENVEOF
# === CONTRACT ADDRESSES (Chain: $CHAIN_ID) ===
# Auto-generated by scripts/sync-addresses.sh — DO NOT EDIT MANUALLY
LENDING_POOL_ADDRESS=$LENDING_POOL
POOL_ADDRESS=$LENDING_POOL
STRATEGY_VAULT_ADDRESS=$STRATEGY_VAULT
VAULT_ADDRESS=$STRATEGY_VAULT
PRICE_ORACLE_ADDRESS=$PRICE_ORACLE
TOKEN_REGISTRY_ADDRESS=$TOKEN_REGISTRY
COMPOSER_ADDRESS=$COMPOSER
SWAP_ROUTER_ADDRESS=$SWAP_ROUTER
EXECUTOR_ADDRESS=$EXECUTOR
STRATEGY_EXECUTOR_ADDRESS=$STRATEGY_EXECUTOR
STRATEGY_REGISTRY_ADDRESS=$STRATEGY_REGISTRY
REGISTRY_ADDRESS=$STRATEGY_REGISTRY
GOVERNOR_ADDRESS=$GOVERNOR
TIMELOCK_ADDRESS=$TIMELOCK

# === TOKEN ADDRESSES ===
TOKEN_WETH=$WETH
TOKEN_USDC=$USDC

# === RPC ===
COFHE_RPC=https://sepolia-rollup.arbitrum.io/rpc

# === SUPABASE ===
SUPABASE_URL=https://igxjqbnsubwiqjhtgigi.supabase.co
SUPABASE_KEY=<your-supabase-service-role-key>

# === AUTH ===
JWT_SECRET=<your-jwt-secret>

# === APY DEFAULTS (BPS) ===
SUPPLY_APY_BPS=650
BORROW_APY_BPS=550

# === OPTIONAL ===
# GEMINI_API_KEY=<your-gemini-api-key>
# SENTRY_DSN=<your-sentry-dsn>
# MAX_LTV=0.75
# EXCHANGE_RATE_WETH_USDC=3000
ENVEOF

echo "Generated: backend/apps/.env.production.example"
echo "Done."
