import { ApiProperty } from "@nestjs/swagger";
import { StrategyStepResponseDto } from "./strategy-step-response.dto";

class ValidationResult {
	@ApiProperty({ example: true, description: "Whether the strategy is valid" })
	isValid: boolean;

	@ApiProperty({
		example: [],
		description: "List of validation errors",
		type: [String],
	})
	errors: string[];

	@ApiProperty({
		example: ["Strategy has high risk due to multiple borrow operations"],
		description: "List of validation warnings",
		type: [String],
	})
	warnings: string[];
}

class AiAnalysis {
	@ApiProperty({
		example: ["High leverage detected", "Multiple borrow operations"],
		description: "List of risk factors identified",
		type: [String],
	})
	riskFactors: string[];

	@ApiProperty({
		example: ["Reduce leverage ratio", "Add stop-loss mechanism"],
		description: "Recommendations to mitigate risks",
		type: [String],
	})
	recommendations: string[];
}

class StrategyMetadata {
	@ApiProperty({ example: 7, description: "Total number of steps" })
	totalSteps: number;

	@ApiProperty({ example: 850000, description: "Estimated gas cost" })
	estimatedGas: number;

	@ApiProperty({
		example: "MEDIUM",
		description: "Risk level of the strategy",
		enum: ["LOW", "MEDIUM", "HIGH"],
	})
	riskLevel: string;

	@ApiProperty({
		example: true,
		description: "Whether the strategy was generated by AI",
	})
	aiGenerated: boolean;
}

export class BuildStrategyResponseDto {
	@ApiProperty({
		type: [StrategyStepResponseDto],
		description: "List of executable strategy steps",
	})
	steps: StrategyStepResponseDto[];

	@ApiProperty({
		type: ValidationResult,
		description: "Validation results for the strategy",
	})
	validation: ValidationResult;

	@ApiProperty({
		type: StrategyMetadata,
		description: "Metadata about the strategy",
	})
	metadata: StrategyMetadata;

	@ApiProperty({
		type: AiAnalysis,
		description: "AI analysis of the strategy",
		required: false,
	})
	aiAnalysis?: AiAnalysis;
}
